GET https://api-lifecycle-gateway.azurewebsites.net/api-doc

###

POST https://api-lifecycle-gateway.azurewebsites.net/v1/rfqs
Content-Type: application/json

{
    "id": "{{$random.uuid}}",
    "name": "string",
    "price": 1001
}