name: Build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/predic8/api-lifecycle-gateway
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{major}},value=v${{github.run_number}}.2.3
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lifecycle-membrane-gw'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZ_PUBLISH_PROFILE }}
          images: "ghcr.io/predic8/api-lifecycle-gateway:${{github.run_number}}"
